import { useRegisterSW } from "virtual:pwa-register/react";

const CHECK_EVERY_MS = 60 * 60 * 1000; // 1 hour

/**
 * Registers the service worker and shows "New version available" when a new deploy is waiting.
 * (virtual:pwa-register/react is generated by vite-plugin-pwa; in `npm run dev` it does nothing.)
 */
export default function UpdatePrompt() {
  const {
    needRefresh: [needRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    // The browser only checks for a new service worker on a full page load. This app rarely reloads
    // (React Router changes pages without one), so also check every hour while it's open.
    onRegisteredSW(_url, registration) {
      if (registration) setInterval(() => registration.update(), CHECK_EVERY_MS);
    },
  });

  if (!needRefresh) return null;
  return (
    <div className="app-banner update-banner" role="status">
      <span>New version available</span>
      {/* true = activate the waiting service worker, then reload the page with the new files */}
      <button type="button" onClick={() => updateServiceWorker(true)}>
        Reload
      </button>
    </div>
  );
}
